CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL,
    [UserName] VARCHAR(50) NOT NULL, 
    [FirebaseUID] VARCHAR(50) NOT NULL
)
